name: Backend Build & Deploy
on:
  push:
    branches:
      - feature/containerization # dev
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
          context: backend/
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Run remote update script
        run: >
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -- sh -s << 'EOF'
            echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            /opt/schedu-web/update-schedu.sh backend
            docker logout ghcr.io
          EOF
